### ISSUE TITLE
Make Better Meaning for Giorno 

### ISSUE THREAD

**Issue by Lockscout** [FRC2706/giorno#14]
While Giorno brings life, that acronym makes me want to die

**Comment by crabctrl** [comment]
Acronyms are hard and we clearly already put a lot of work into this one. Honestly, I don't see what the problem is. Its descriptive, it's concise, what more could you possibly want?

...If you have suggestions feel free to make them

**Comment by crabctrl** [comment]
That said, you *may* be on to something...
